services:
  - type: web
    name: ml-project-fast-api-app
    repo: https://github.com/ADBondarenko/ML_stock_prediction_project
    numInstances: 1   # Manual scaling configuration. Default: 1
    region: frankfurt # Default: oregon
    plan: starter    # Default: starter
    env: docker
    dockerCommand: tree/main/service/DockerfileAPI
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    envVars: # Environment variables
      - fromGroup: ml-project-api-bot # Add all variables from an environment group
  - type: web
    name: ml-project-bot-app
    repo: https://github.com/ADBondarenko/ML_stock_prediction_project #render.yaml
    numInstances: 1   # Manual scaling configuration. Default: 1
    region: frankfurt # Default: oregon
    plan: starter    # Default: starter
    env: docker
    dockerCommand: tree/main/bot_tg/DockerfileBOT
    maxShutdownDelaySeconds: 120 # Increase graceful shutdown period. Default: 30, Max: 300
    envVars: # Environment variables
      - fromGroup: ml-project-api-bot # Add all variables from an environment group